POST http://127.0.0.1:3000/users HTTP/1:1
Content-Type: application/json

{
    "name": "Gabriel de Souza Nunes",
    "email": "gabrielsouza.iacs@gmail.com",
    "password": "icpv3html",
    "accessLevel": "admin"
}

###

GET http://127.0.0.1:3000/users

###

GET http://127.0.0.1:3000/users/search?id=25955ed3-570e-4ec4-a335-d0383a6c1442

###

GET http://127.0.0.1:3000/users/search?name=Gabriel

###

GET http://127.0.0.1:3000/users/search?email=gabrielsouza.nunes@hotmail.com

###

PUT http://127.0.0.1:3000/users HTTP/1:1
Content-Type: application/json

{
    "id": "25955ed3-570e-4ec4-a335-d0383a6c1442",
    "name": "Gabriel Souza",
    "password": "icpv3html"
}

###

DELETE http://127.0.0.1:3000/users HTTP/1:1
Content-Type: application/json

{
    "id": "25955ed3-570e-4ec4-a335-d0383a6c1442"
}